### PR TITLE
📝 Add info on running with "before" script

### PR DESCRIPTION
**Pull request by grdryn**

### CODE REVIEW

**Comment by grdryn** [comment]
@paolobueno @wojta could you please review? The bump to load-runner is to facilitate running the setup script as part of the load-runner execution, and the README now has an example of doing that.

**Review by paolobueno — APPROVED** [review]

**Comment by paolobueno** [comment]
Quite a collection of params!

**Comment by grdryn** [comment]
@paolobueno yep! The ones on the last line, after the `--` are the params to the main script (and the `before` script inherits both the main script params, and some of the params to `load-runner` itself). :)

Thanks for the review!

**Comment by wojta** [comment]
fine for me

**Review by wojta — COMMENTED** [review]
fine for me

**Pull request merged**
