### PR TITLE
[RAINCATCH-645] Add data reset command

### PR DESCRIPTION
**Pull request by paolobueno**

### CODE REVIEW

**Comment by paolobueno** [comment]
@grdryn I've added the command as a separate script. Do you think it should also be available as a method to use in the other scripts?

**Review by grdryn — APPROVED** [review]
@paolobueno LGTM. How do you feel about having this run as part of the setup script that's passed to load-runner? E.g. the `setup/usersWorkorders.js` or something that wraps both this and that?

**Comment by paolobueno** [comment]
@grdryn I see what you mean. Checked the source code for `load-runner --before` and it spawns `node $before` and forward the params from the rest of the script. I'll add a wrapper around both of these then.

**Comment by paolobueno** [comment]
@grdryn added the wrapper script, could you take another quick look?

**Comment by paolobueno** [comment]
Actually I'll go ahead and merge these, we can make small adjustments later.

**Pull request merged**
